services:
  ast-audio-classifier:
    image: ast-audio-classifier:jupyterlab
    build:
      context: .
    ports:
      - "8888:8888"  # Map JupyterLab to port 8888
    volumes:
      - ./app:/app  # Mount the entire app directory into the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]  # Enable GPU access
    runtime: nvidia  # Use NVIDIA runtime for GPU