services:
  jupyter-lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./tf:/tf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
